server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
   
spring:
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/soulmate?serverTimezone=Asia/Seoul
    username: tmdghks
    password: 123456
    
  jpa:
    open-in-view: true
    hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
                
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 591330623010-vjrig8mv1oq90rfdg4ilmkkq0sionisi.apps.googleusercontent.com
            client-secret: JxmWyCUt_lLihv5aN1s0I7h-
            scope:
            - email
            - profile
          facebook:
            client-id: 1547951888729043
            client-secret: 4a2e4fb1db7924b03cb886916665ae86
            scope:
            - email
            - public_profile
          naver:
            client-id: Kv8b2dbsH37bpGH3VURS
            client-secret: CjYD2D__1Y
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9999/login/oauth2/code/naver
          kakao:
            client-id: bde85298a1ddb8bf94adec31c1643573
            client-secret: BnUtRmBKZ16xl4ik4Q1YHYdehm7MFfQc
            scope:
            - profile
            - account_email
            client-name: Kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9999/login/oauth2/code/kakao
            
        provider:
          naver: 
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response 
          kakao: 
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account 
